#!/usr/bin/env python3
"""run_tests.py - offline tests for the TX mod: real mod scripts on a fake Civ VI engine.

Runs tests/offline/test_*.lua on lupa's Lua 5.1 runtime with lib/fake_engine.lua,
lib/fake_ui.lua and lib/harness.lua. Every test gets a fresh Lua state.

Usage:
    python tests/offline/run_tests.py                 # syntax check + all tests
    python tests/offline/run_tests.py -k vote         # only tests whose file/name contains "vote"
    python tests/offline/run_tests.py -v              # logs/tracebacks of failures and xfails
    python tests/offline/run_tests.py --echo -k name  # stream the Lua log while running
    python tests/offline/run_tests.py --list          # list tests
    python tests/offline/run_tests.py --regen         # rebuild data/gameinfo_data.lua from the game DB

Results:
    PASS   test passed.
    FAIL   assertion failed / Lua error / logged ERROR lines / handler errors, in a test that is
           not explicitly marked expected-fail.
    SKIP   the test called H.skip(reason) or H.needGameInfo() without the game data, or the
           file starts with a "-- @needs gameinfo" line and the data is missing.
    XFAIL  failed, and the test is marked xfail with a reason that names the pending work:
               test("name", fn, xfail("Phase 2 (WP2.1): vote popup"))
           A mark whose reason names no "WPx.y" / "Phase N" is rejected (FAIL).
    XPASS  marked xfail but passed (remove the mark).
Exit code: 0 if no FAIL and no syntax error, 1 otherwise, 2 on setup problems.

GameInfo comes from the game's cached DB (Cache/DebugGameplay.sqlite, see tools/txlib.py), exported
to tests/offline/data/gameinfo_data.lua (gitignored; rebuilt when the DB is newer). Without the game
the file is missing: GameInfo then only has Types rows for the mod's own notification types, read
from TX/ and TX_Dev/ SQL, and tests that need more call H.needGameInfo() (they SKIP).
Text comes from the LocalizedText rows of every XML file under TX/ and TX_Dev/.
"""
from __future__ import annotations

import argparse
import re
import sqlite3
import sys
import time
import xml.etree.ElementTree as ET
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import txlib  # noqa: E402

DATA_LUA = HERE / "data" / "gameinfo_data.lua"
MOD_DIRS = list(txlib.MOD_FOLDERS)                 # searched for include() and texts, in this order
SYNTAX_DIRS = MOD_DIRS + ["tests/offline"]

# table -> (primary key column, row filter SQL or None). Tables missing from the DB are skipped.
EXPORT_TABLES = {
    "Types": ("Type", "Kind IN ('KIND_NOTIFICATION','KIND_CIVILIZATION','KIND_LEADER','KIND_VICTORY',"
                      "'KIND_DIPLOMATIC_STATE','KIND_GAMESPEED','KIND_TECH','KIND_CIVIC')"),
    "Notifications": ("NotificationType", None),
    "Civilizations": ("CivilizationType", None),
    "Leaders": ("LeaderType", None),
    "Victories": ("VictoryType", None),
    "DiplomaticStates": ("StateType", None),
    "GameSpeeds": ("GameSpeedType", None),
    "Technologies": ("TechnologyType", None),
    "Civics": ("CivicType", None),
}


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------
def fnv1a_signed(s: str) -> int:
    h = 2166136261
    for ch in s.encode("utf-8"):
        h ^= ch
        h = (h * 16777619) % 4294967296
    return h - 4294967296 if h >= 2147483648 else h


def lua_quote(s: str) -> str:
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif o < 32 or o == 127:
            out.append("\\%03d" % o)
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def lua_value(v):
    if v is None:
        return "nil"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    return lua_quote(str(v))


def export_gameinfo(db: Path, out: Path):
    con = sqlite3.connect("file:%s?mode=ro" % db.as_posix(), uri=True)
    type_hash = {t: h for t, h in con.execute("SELECT Type, Hash FROM Types")}
    lines = ["-- Generated by tests/offline/run_tests.py from %s. Do not edit, do not commit." % db.name, "return {"]
    for table, (pk, where) in EXPORT_TABLES.items():
        cols = list(con.execute("PRAGMA table_info(%s)" % table))
        if not cols:
            continue
        names = [c[1] for c in cols]
        booleans = {c[1] for c in cols if (c[2] or "").upper() == "BOOLEAN"}
        sql = "SELECT * FROM %s" % table + (" WHERE " + where if where else "") + " ORDER BY rowid"
        lines.append("  %s = { pk = %s, rows = {" % (table, lua_quote(pk)))
        for row in con.execute(sql):
            fields = []
            rec = dict(zip(names, row))
            for k in names:
                v = rec[k]
                if v is None:
                    continue
                if k in booleans:
                    v = bool(v)
                fields.append("%s=%s" % (k, lua_value(v)))
            if "Hash" not in rec:
                key = rec.get(pk)
                if key is not None:
                    fields.append("Hash=%d" % type_hash.get(key, fnv1a_signed(str(key))))
            lines.append("    {" + ",".join(fields) + "},")
        lines.append("  } },")
    lines.append("}")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    con.close()


def mod_files(pattern):
    for d in MOD_DIRS:
        base = ROOT / d
        if base.is_dir():
            yield from sorted(base.rglob(pattern))


def load_text() -> dict:
    """en_US LocalizedText rows of every XML file under TX/ and TX_Dev/."""
    texts = {}
    for path in mod_files("*.xml"):
        try:
            tree = ET.parse(path)
        except ET.ParseError as e:
            print("WARN: cannot parse %s: %s" % (path.relative_to(ROOT).as_posix(), e))
            continue
        for row in tree.iter():
            if row.tag not in ("Row", "Replace"):
                continue
            tag = row.get("Tag")
            lang = row.get("Language") or "en_US"
            text_el = row.find("Text")
            text = text_el.text if text_el is not None else row.get("Text")
            if tag and text is not None and lang == "en_US":
                texts[tag] = text
    return texts


NOTIF_SQL = re.compile(r"'([A-Za-z0-9_]+)'\s*,\s*'KIND_NOTIFICATION'")


def extra_types() -> list:
    """KIND_NOTIFICATION types the mod inserts (SQL rows and XML <Row Type= Kind=>)."""
    names = set()
    for path in mod_files("*.sql"):
        names.update(NOTIF_SQL.findall(path.read_text(encoding="utf-8", errors="replace")))
    for path in mod_files("*.xml"):
        try:
            tree = ET.parse(path)
        except ET.ParseError:
            continue
        for row in tree.iter("Row"):
            if row.get("Kind") == "KIND_NOTIFICATION" and row.get("Type"):
                names.add(row.get("Type"))
    return sorted(names)


def read_rel(rel):
    p = ROOT / str(rel)
    if p.is_file():
        return p.read_text(encoding="utf-8", errors="replace")
    return None


_INCLUDE_INDEX = None


def find_include(name):
    """include() resolves by file name (the engine's ImportFiles are flat): TX/, TX_Dev/, then tests/offline/lib."""
    global _INCLUDE_INDEX
    if _INCLUDE_INDEX is None:
        _INCLUDE_INDEX = {}
        for p in list(mod_files("*.lua")) + sorted((HERE / "lib").glob("*.lua")):
            _INCLUDE_INDEX.setdefault(p.stem.lower(), p.relative_to(ROOT).as_posix())
    name = str(name)
    base = name[:-4] if name.lower().endswith(".lua") else name
    return _INCLUDE_INDEX.get(Path(base).name.lower())


# ---------------------------------------------------------------------------
# Lua runtime
# ---------------------------------------------------------------------------
class Env:
    def __init__(self, echo=False):
        import lupa.lua51 as lua51
        self.lua51 = lua51
        self.echo = echo
        self.text = load_text()
        self.types = extra_types()
        self.has_data = DATA_LUA.exists()

    def runtime(self):
        rt = self.lua51.LuaRuntime(unpack_returned_tuples=True)
        g = rt.globals()
        g["__py_read"] = read_rel
        g["__py_find"] = find_include
        g["__py_echo"] = lambda s: print("      | " + str(s))
        g["FAKE_TEXT"] = rt.table_from(self.text)
        g["FAKE_EXTRA_TYPES"] = rt.table_from(self.types)
        g["__has_data"] = self.has_data
        rt.execute(BOOT)
        g["FAKE"]["echo"] = self.echo
        return rt


BOOT = r"""
local function load(rel)
  local src = __py_read(rel)
  if src == nil then error("missing " .. rel) end
  local f, e = loadstring(src, "@" .. rel)
  if not f then error(e) end
  return f()
end
load("tests/offline/lib/fake_engine.lua")
FAKE.LoadGameInfo(__has_data and load("tests/offline/data/gameinfo_data.lua") or nil, FAKE_EXTRA_TYPES)
load("tests/offline/lib/fake_ui.lua")
load("tests/offline/lib/harness.lua")

function __load_test_file(rel)
  local src = __py_read(rel)
  local f, e = loadstring(src, "@" .. rel)
  if not f then return false, e end
  local ok, ret = xpcall(f, debug.traceback)
  if not ok then return false, ret end
  return true, nil
end

function __test_names()
  local out = {}
  for i, t in ipairs(TESTS) do out[i] = t.name end
  return out
end

function __test_opts(name)
  for _, t in ipairs(TESTS) do
    if t.name == name then
      return t.opts.xfail, t.opts.allowErrors and true or false
    end
  end
  return nil, false
end

function __run_named(name)
  local fn
  for _, t in ipairs(TESTS) do if t.name == name then fn = t.fn end end
  if fn == nil then return false, "test not found: " .. name end
  if FAKE.bodyStart == nil then FAKE.bodyStart = #FAKE.log end
  local ok, err = xpcall(fn, debug.traceback)
  return ok, err
end

function __log_lines(from)
  local out = {}
  for i = (from or 0) + 1, #FAKE.log do out[#out + 1] = FAKE.log[i] end
  return out
end
"""


def lua_list(tbl):
    if tbl is None:
        return []
    out = []
    i = 1
    while True:
        v = tbl[i]
        if v is None:
            break
        out.append(v)
        i += 1
    return out


def needs_gameinfo(path: Path) -> bool:
    with open(path, encoding="utf-8", errors="replace") as f:
        head = [f.readline() for _ in range(5)]
    return any(re.match(r"^--\s*@needs\s+gameinfo\b", ln) for ln in head)


# ---------------------------------------------------------------------------
# Syntax check (Lua 5.1 loadstring over every .lua file of the mod and the tests)
# ---------------------------------------------------------------------------
def syntax_check(env):
    rt = env.lua51.LuaRuntime(unpack_returned_tuples=True)
    comp = rt.eval("function(src, name) local f, e = loadstring(src, name) return f ~= nil, e end")
    errors, count = [], 0
    for d in SYNTAX_DIRS:
        base = ROOT / d
        if not base.exists():
            continue
        for p in sorted(base.rglob("*.lua")):
            if p == DATA_LUA:
                continue
            count += 1
            rel = p.relative_to(ROOT).as_posix()
            src = p.read_text(encoding="utf-8", errors="replace")
            ok, err = comp(src, "@" + rel)
            if not ok:
                errors.append("%s: %s" % (rel, err))
            # Havok-only type annotation: "local x : number"
            for ln, line in enumerate(src.splitlines(), 1):
                code = line.split("--", 1)[0]
                if re.search(r"\blocal\s+\w+\s*:\s*\w+", code):
                    errors.append("%s:%d: type annotation (Havok-only syntax)" % (rel, ln))
    return count, errors


# ---------------------------------------------------------------------------
# Running
# ---------------------------------------------------------------------------
class Result:
    def __init__(self, file, name, status, detail="", log=None, xfail=None):
        self.file, self.name, self.status, self.detail = file, name, status, detail
        self.log = log or []
        self.xfail = xfail


# An xfail reason must name the pending work (a work package or phase).
XFAIL_REASON = re.compile(r"\bWP\d+(\.\d+)?\b|\bPhase \d+\b")
SKIP_RE = re.compile(r"^(?:[^\n]*?: )?SKIP (.*)", re.S)


def error_lines(lines):
    # "[TX][X] ERROR ..." and the TX_Dev shape "[TX][SPIKE][X] G|UI ERROR ..."
    return [ln for ln in lines if re.search(r"\]\[[^\]]+\] (?:(?:G|UI) )?ERROR ", ln) or "Runtime Error" in ln]


def run_one(env, rel, name):
    rt = env.runtime()
    g = rt.globals()
    ok, err = g["__load_test_file"](rel)
    if not ok:
        return Result(rel, name, "FAIL", "test file failed to load: %s" % err)
    xfail, allow_errors = g["__test_opts"](name)
    ok, err = g["__run_named"](name)
    body = lua_list(g["__log_lines"](g["FAKE"]["bodyStart"] or 0))
    handler_errors = lua_list(g["FAKE"]["handlerErrors"])
    detail = ""
    passed = bool(ok)
    if not passed:
        detail = str(err)
    elif not allow_errors:
        errs = error_lines(body)
        if errs:
            passed = False
            detail = "logged errors (swallowed by pcall):\n" + "\n".join(errs[:8])
    if passed and handler_errors and not allow_errors:
        passed = False
        detail = "event handler errors:\n" + "\n".join(handler_errors[:8])
    status, detail, xfail = classify(passed, detail, xfail, [])
    return Result(rel, name, status, detail, body, xfail)


def classify(passed, detail, xfail, stubs):
    """Result status of one test -> (status, detail, xfail).

    SKIP when the test raised H.skip(reason). XFAIL only for a failing test with an explicit
    xfail mark whose reason names the pending work package or phase. `stubs` (names of stub
    functions hit) is shown as a hint and never excuses a failure."""
    if not passed and detail:
        m = SKIP_RE.match(str(detail))
        if m:
            return "SKIP", m.group(1).split("\n", 1)[0], None
    if xfail is not None and not XFAIL_REASON.search(str(xfail)):
        passed = False
        detail = ("xfail mark %r names no pending work package ('WPx.y') or phase ('Phase N')\n"
                  % str(xfail)) + (detail or "")
        xfail = None
    if passed:
        return ("XPASS" if xfail else "PASS"), detail, xfail
    if xfail:
        return "XFAIL", "[marked xfail: %s] %s" % (xfail, detail), xfail
    if stubs:
        detail = "(stubs hit, not an excuse: %s)\n%s" % (", ".join(stubs[:4]), detail)
    return "FAIL", detail, None


def discover(env, path: Path):
    rel = path.relative_to(ROOT).as_posix()
    rt = env.runtime()
    g = rt.globals()
    ok, err = g["__load_test_file"](rel)
    if not ok:
        return rel, None, Result(rel, "<load>", "FAIL", "test file failed: %s" % err)
    return rel, lua_list(g["__test_names"]()), None


def main(argv=None):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-k", dest="filter", default=None, help="substring filter on file or test name")
    ap.add_argument("-v", "--verbose", action="store_true", help="details for FAIL and XFAIL")
    ap.add_argument("--echo", action="store_true", help="stream Lua print output while running")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--regen", action="store_true", help="re-export GameInfo from the game DB")
    ap.add_argument("--db", default=txlib.GAMEPLAY_DB, help="gameplay DB (default: the game's cache)")
    ap.add_argument("--no-syntax", action="store_true")
    a = ap.parse_args(argv)

    try:
        import lupa.lua51  # noqa: F401
    except Exception as e:  # pragma: no cover
        print("run_tests: lupa with Lua 5.1 is required (pip install lupa): %s" % e)
        return 2

    db = Path(a.db) if a.db else None
    if db is not None and db.exists() and (a.regen or not DATA_LUA.exists() or db.stat().st_mtime > DATA_LUA.stat().st_mtime):
        export_gameinfo(db, DATA_LUA)
        print("run_tests: exported GameInfo from %s" % db)
    elif a.regen:
        print("run_tests: game DB not found (%s), nothing to export" % db)
    if not DATA_LUA.exists():
        print("run_tests: note: no game data (%s); tests that need GameInfo are skipped"
              % DATA_LUA.relative_to(ROOT).as_posix())

    t0 = time.time()
    env = Env(echo=a.echo)
    syntax_errors = []
    if not a.no_syntax:
        n, syntax_errors = syntax_check(env)
        print("== Lua 5.1 syntax: %d file(s), %d error(s)" % (n, len(syntax_errors)))
        for e in syntax_errors:
            print("   SYNTAX " + e)

    files = sorted(HERE.glob("test_*.lua"))
    results = []
    for path in files:
        rel = path.relative_to(ROOT).as_posix()
        if needs_gameinfo(path) and not env.has_data:
            if a.filter is None or a.filter.lower() in rel.lower():
                print("== %s" % rel)
                r = Result(rel, "<file>", "SKIP", "needs gameinfo_data.lua (game DB)")
                results.append(r)
                print("  %-6s %s  (%s)" % (r.status, r.name, r.detail))
            continue
        rel, names, early = discover(env, path)
        if early is not None:
            if a.filter is None or a.filter.lower() in rel.lower():
                results.append(early)
                print("== %s" % rel)
                print("  %-6s %s" % (early.status, early.name))
                for ln in early.detail.strip().splitlines()[:12]:
                    print("         " + ln)
            continue
        selected = [n for n in names if a.filter is None or a.filter.lower() in (rel + " " + n).lower()]
        if not selected:
            continue
        print("== %s" % rel)
        for name in selected:
            if a.list:
                print("         %s" % name)
                continue
            if a.echo:
                print("  ...    %s" % name)
            r = run_one(env, rel, name)
            results.append(r)
            extra = ""
            if r.status in ("XFAIL", "XPASS"):
                extra = "  [xfail: %s]" % r.xfail
            elif r.status == "SKIP":
                extra = "  (%s)" % r.detail
            print("  %-6s %s%s" % (r.status, name, extra))
            show = r.status == "FAIL" or (a.verbose and r.status == "XFAIL")
            if show and r.detail:
                lines = r.detail.strip().splitlines()
                limit = 40 if a.verbose else 12
                for ln in lines[:limit]:
                    print("         " + ln)
            if a.verbose and r.status in ("FAIL", "XFAIL") and r.log:
                print("         -- log (last 25 lines) --")
                for ln in r.log[-25:]:
                    print("         | " + ln)
    if a.list:
        return 0
    counts = {}
    for r in results:
        counts[r.status] = counts.get(r.status, 0) + 1
    dt = time.time() - t0
    print()
    print("== Summary: %d passed, %d failed, %d skipped, %d xfail, %d xpass; %d test(s) in %d file(s), %.1fs%s" % (
        counts.get("PASS", 0), counts.get("FAIL", 0), counts.get("SKIP", 0), counts.get("XFAIL", 0),
        counts.get("XPASS", 0), len(results), len(files), dt,
        ("; %d SYNTAX error(s)" % len(syntax_errors)) if syntax_errors else ""))
    ok = not counts.get("FAIL") and not syntax_errors
    print("== %s" % ("PASS" if ok else "FAIL"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
